export interface nomfModel{
    COD :string,
    NUME :string,
    CODAUX :string,
    LOCALITATE :string,
    JUDET :string,
    OBS :string,
    STR :string,
    POSTAL :string,
    TEL :string,
    FAX :string,
    PAR :string,
    CAEN :string,
    STCEG :string,
    BRSCG :number,
    VKBUR:string,
    VKGRP :string,
    KDGRP :string,
    KTGRD:string,
    NR :string,
    BLOC :string,
    SCARA :string,
    ETAJ :string,
    AP :string,
    SECTOR :string,
    UACCES :string,
    FOTOGRAFIE :string,
    TARA :string,
    TIP :string,
    ORC :string,
    CAPITAL_SOCIAL :number,
    CF_PARINTE :string,
    EMAIL :string,
    BI :string,
    POLITIA :string,
    NIR: number,
    CETATENIE :string,
    TIP_CI :string,
    TIP_AUTORIZ :string,
    DATA_IAU :string,
    DATA_SFA :string,
    OBS_FACT :string,
    CALITATE :string,
    WEB :string
  }